services:
  pelican:
    image: ghcr.io/pelican-dev/panel:main
    restart: always
    environment:
      TZ: Europe/Oslo
      APP_URL: http://pelican.heka.no
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      APP_DEBUG: true
      APP_ENV: production
      XDG_DATA_HOME: /pelican-data
      TRUSTED_PROXIES: "*"
    ports:
      - "127.0.0.1:9001:80"
    volumes:
      - ./data/pelican:/pelican-data
      - ./data/logs:/var/www/html/storage/logs
      - ./data/Caddyfile:/etc/caddy/Caddyfile