services:
  wings:
    image: ghcr.io/pelican-dev/wings:latest
    restart: always
    networks:
      - wings0
    ports:
      - "127.0.0.1:9002:8080"
      - "2022:2022"
    environment:
      TZ: "Europe/Oslo"
      WINGS_UID: 988
      WINGS_GID: 988
      WINGS_USERNAME: pelican
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/lib/docker/containers/:/var/lib/docker/containers/"
      - "/etc/pelican/:/etc/pelican/"
      - "/var/lib/pelican/:/var/lib/pelican/"
      - "/var/log/pelican/:/var/log/pelican/"
      - "/tmp/pelican/:/tmp/pelican/"

networks:
  wings0:
    name: wings0
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: wings0